# docker-compose.staging.yml
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: horarios_cursado
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: tu_password
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usuario -d horarios_cursado"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./backend/cruma
      dockerfile: Dockerfile
    env_file:
      - .env.staging     # define DB_HOST=db, DB_PORT=5432, etc.
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health/liveness"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "8080:8080"

volumes:
  db_data:
