version: '3.8'

services:
  db:
    image: postgres:15                # fija una versión mayor estable
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data  # persistencia de datos
      - ./db/initdb:/docker-entrypoint-initdb.d # inicialización automática
    ports:
      - "${DB_PORT}:5432"
    networks:
      - backend
    healthcheck:                        # chequea que Postgres esté listo
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cruma-app
    env_file:
      - .env
    # Defino vars para Spring Boot
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:${DB_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: ${DB_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:                       # volumen nombrado para datos

networks:
  backend:                            # red interna para los servicios
