version: "3.9"
services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file: .env 
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro

volumes:
  pgdata:

